#!/bin/sh

if [ ! -e $HOME/.vim/bundle/vundle ]; then
  git clone https://github.com/gmarik/vundle.git $HOME/.vim/bundle/vundle
fi
vim +BundleInstall +qa

if [ ! -e $HOME/.config/base16-shell ]; then
  mkdir -p .config
  git clone git@github.com:chriskempson/base16-shell.git ~/.config/base16-shell
fi
